### ISSUE TITLE
Mapping existing site-wide headers into origin-policy

### ISSUE THREAD

**Issue by mnot** [mikewest/origin-policy#16]
Assuming that #14 is accepted, a (probably incomplete) list of candidates:

* `Strict-Transport-Security`
* `Public-Key-Pins`
* `Public-Key-Pins-Report-Only`
* `Expect-CT`
* `Content-Security-Policy` (not always site-wide)
* `Server`
* `P3P`
* `Access-Control-Allow-Origin` (not always site-wide)
* `Alt-Svc` (???)

**Comment by mnot** [comment]
... and the easiest way to do this would be to define each as a member of the origin-policy object, using the header name (lowercase normalised) as the key, and the on-the-wire header field syntax as a JSON string (appropriately escaped, of course) for a value.

However, if the answer to this is "none of them" -- i.e., origin-policy is only for new things -- we can get rid of `Vary` on the response, because the response won't change based on whether the client supports origin-policy. It also greatly simplifies the server-side implementation (no determining which headers to send on a response-by-response basis). 

Looking at the list above, a few notes (and thinking out loud):

* `P3P` is really only emitted for old versions of IE; new browsers don't consume it AFAIK, so it's never going to be useful to put it into origin-policy.
* It's *probably* safe to omit `Server` in headers and put it in origin-policy for those that are interested (i.e., don't negotiate, just move it). Needs some testing.
* `Alt-Svc` in origin-policy feels a bit weird, and probably should be avoided. I suppose it might be useful for things like OppSec, but it might be a source of many bugs (since both origins will probably be backed by the same filesystem).
* `Public-Key-Pins` and `Public-Key-Pins-Report-Only` adoption is really low, so a migration strategy is probably appropriate.
* `Expect-CT` isn't out yet, so if we can do this quickly, it's not a concern.
* `Access-Control-Allow-Origin` seems like it's supplanted by `cors-preflight` and `unsafe-cors-preflight-with-credentials`, no?

That leaves `Strict-Transport-Security` and `Content-Security-Policy` (and anything else I missed).

CSP has always been an awkward fit for a site-wide mechanism, because it's very often not site-wide, and the header combination semantics mean you can't really set a site-wide policy and then refine it with response headers. OTOH, due to its size CSP is a big candidate for this type of mechanism.

It seems like we almost need a mechanism where you can define a bunch of pre-cooked policies (or policy components) for CSP in origin-policy, and then refer to them in response headers, triggered by the presence of a request header. This would give flexibility as well as good byte savings. However, it goes back to a negotiation pattern, which is more complex on both sides of the wire. Perhaps limiting it to just CSP mitigates that a bit.

Regarding STS, I'm not sure the modest byte savings are worth a negotiation mechanism. I'd almost rather just define the origin-policy member for it, and sites can stop emitting the STS header a while (few years?) down the road, when adoption is sufficient (and browsers that don't support it are likely to be insecure in other, newly-discovered ways).

Thoughts?

**Comment by Malvoz** [comment]
@mnot 

> Assuming that #14 is accepted, a (probably incomplete) list of candidates:
> 
> Strict-Transport-Security
> Public-Key-Pins
> Public-Key-Pins-Report-Only
> Expect-CT
> Content-Security-Policy (not always site-wide)
> Server
> P3P
> Access-Control-Allow-Origin (not always site-wide)
> Alt-Svc (???)

To add to the list, here are some other widely used headers that comes to mind:

`AddCharset`
`AddDefaultCharset`
`AddEncoding`
`AddType`
`Cache-Control` (and `Expires`)
`Content-Language`
`ErrorDocument`
`Rewrite`
`ServerSignature`
`X-Content-Type-Options`
`X-Frame-Options`
`X-Powered-By`
`X-XSS-Protection`

I should add that I don't really comprehend the scope of origin-policy, is it intended to be a substitute for e.g. `.htaccess`?

**Comment by domenic** [comment]
Thanks for the analysis here!

It seems like all the ones that we might realistically use are already listed in https://github.com/WICG/origin-policy/blob/master/policy-format.md#supported-policy-items , so I think we're good to go. I'll close this issue for now, although I'm happy to reopen if you think we should say more.
