### ISSUE TITLE
Manifest revocation vs header revocation

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#18]
**Issue:** revoking the manifest does not automatically revoke the effects of manifest included headers, e.g. HSTS, which can easily lead to confusion and misconfigurations.

**Proposal:**
allow to add the following to the object
`“on-revoke”: {
  <chance to invalidate HSTS etc here>
}`
it allows to define what to invalidate when invalidating the manifest itself.

**Comment by mikewest** [comment]
As noted in one of the other bugs, I'm imagining that headers that currently have a `max-age` will not have such a property when implemented via this manifest. If we assert that an origin is HTTPS-only via the manifest, that assertion should only live as long as the manifest.

If that's the case, is the `on-revoke` necessary?

**Comment by dhausknecht** [comment]
what I was looking for is that the lifespan of what ever we control through the manifest is somehow revoked or at least revocable. So yes, I'd gladly agree if we say everything that has a life dies with the manifest as soon as it is defined in there.
Also to be explicit, I'd prefer to treat baseline and fallback equally. That is no matter in which mode it appears in a manifest, it dies with the manifest. For example, we never actually used the fallback case for a header because everything was always in the response anyway, it still gets revoked.

> If that's the case, is the on-revoke necessary?

No.

**Comment by domenic** [comment]
I think with the movement away from baseline/fallback separation, plus the above points about how manifest lifetime helps, this is no longer as applicable. I'll add a clarification to the explainer that we explicitly expect things to no longer be applied once the manifest no longer applies, to close this out. (And I'll be sure to incorporate that while speccing!)
