### ISSUE TITLE
Define a mechanism to pin a dynamic policy?

### ISSUE THREAD

**Issue by mikewest** [mikewest/origin-policy#2]
It would be nice to come up with a recommended mechanism for pinning policies that include nonces. On the one hand, this can be verbosely dealt with via a combination of `baseline` and `fallback` policies in the current syntax:

```
{
  ...
  "csp": [
    {
      "policy": "script-src 'none'",
      "type": "fallback"
    },
    {
      "policy": "object-src 'none'",
      "type": "baseline"
    }
  ],
  ...
}
```

The latter would be applied to every request, the former only to those that don't set their own policy. So, a page that delivered `Content-Security-Policy: script-src 'nonce-yay' 'strict-dynamic'` would end up with a policy of `script-src 'nonce-yay' 'strict-dynamic', object-src 'none'`, which would merge into reasonable behavior.

Actually, maybe that's not so bad, now that I spell it out... I'm not sure a template system merging in additional response headers is any better, and it might be significantly worse/more complex.

**Comment by mikewest** [comment]
+@ptoomey3 and @intchloe who discussed this in #1.

**Comment by ptoomey3** [comment]
Do `Content-Seucrity-Policy` provided directives completely override what is in the baseline policy? 

```
{
  ...
  "headers": {
    "fallback": [
      {
        "name": "Content-Security-Policy",
        "value": "script-src 'none'"
      }
    ],
    "baseline": [
      {
        "name": "Content-Security-Policy",
        "value": "object-src 'none'; frame-ancestors 'self'"
      }
    ]
  },
  ...
}
```

in combination with:

```
Content-Security-Policy: script-src 'nonce-{nonce-goes-here}' 'strict-dynamic'
```

leads to:

> The baseline policy will be applied to every response, blocking plugins and restricting framing regardless of the response’s other headers.
> The fallback policy will be applied iff the response doesn’t itself provide a Content Security Policy, meaning that the resource’s policy will be applied, the nonce will be active, and script will execute as expected.

I'm not 100% clear on interaction between the header policy and the `baseline` policy. Is the intent to send down the complete policy for a given directive if you want to override anything in the baseline policy? I guess that could work out ok. It wouldn't be the most space efficient solution, but maybe it it the easiest to do without adding lots of complex interactions between CSP and this manifest spec. In the magical world where complexity didn't matter, we would have some means of saying `Content-Security-Policy: add-form-action https://add_a_single_host`. That would be super space efficient, but at the cost of lots of new syntax/complexity. So, with your proposed mechanism, if I'm understanding this correctly, it would work like this: 

```
Content-Security_policy: form-action `self` https://static_trusted_partner_from_existing_manifest https://dynamic_trusted_partner_we_want_to_add_for_this_one_page
```

Is that correct?

**Comment by mikewest** [comment]
The idea is as follows:
- `baseline` headers are appended to every response, period.
- `fallback` headers are appended to every response that doesn't already have the header.

So, given `https://example.com/nonce` which returns

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html
Content-Security-Policy: script-src 'nonce-nonce-goes-here' 'strict-dynamic'
```

the policy above would result in a response that looked like:

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html
Content-Security-Policy: script-src 'nonce-nonce-goes-here' 'strict-dynamic'
Content-Security-Policy: object-src 'none'; frame-ancestors 'self'
```

>  Is the intent to send down the complete policy for a given directive if you want to override anything in the baseline policy? 
1. The "baseline" policy is not overridable. It is always applied.
2. Fallback policies are completely overwritten. For the nonce case, this is straightforward and simple! For your case, it's less so.

But:

> It wouldn't be the most space efficient solution, but maybe it it the easiest to do without adding lots of complex interactions between CSP and this manifest spec.

I am trying to tease out the simplest possible primitive here. I agree that it ends up being wasteful for your needs, but (for better or worse) you're like 800 miles ahead of most other implementations.

So, why don't we do this: open a bug against the repo with your `add-X` strawman, and we'll try to come up with something sane. :)

**Comment by intchloe** [comment]
If we take Github as an example where static resources have `default-src 'none'` - should Github not send a `Content-Security-Policy` header for all static resources to make them use the "fallback" policy stated in the manifest?  

What if Github want `style-src 'unsafe-inline'` for images, but `default-src 'none'` for everything else, and these resources are on the same origin. How can that be solved? 

You could have a "baseline" policy set to `default-src 'none'` and then explicitly send a `Content-Security-Policy` header on stuff that you want a policy on. So we would work the other way as we do today. Still, we would have to do a lot on the web server.

So, the goal of "Origin-Policy" is:
- Applying a CSP all over the site
- Eliminating the need of sending a huge CSP on every request

Correct? I'm fine with that. Just trying to figure out if "Origin-Policy" will make us spend more time on the web server configuration, or the manifest itself.

**Comment by arturjanc** [comment]
FWIW I like this approach, it's probably saner than trying to do templating for nonce-based policies and will have similar security properties.

**Comment by mikewest** [comment]
> What if Github want style-src 'unsafe-inline' for images, but default-src 'none' for everything else, and these resources are on the same origin. How can that be solved?

They can set a fallback of `default-src 'none'` and serve `C-S-P` headers on resources that shouldn't use that value. I'm not sure it's worth introducing the complexity of more granular controls; things that live on an origin all have the same security properties, at core. Distinguishing between paths or MIME types is a losing battle.

> So, the goal of "Origin-Policy" is:
> - Applying a CSP all over the site
> - Eliminating the need of sending a huge CSP on every request

More or less, yes.
