### ISSUE TITLE
Dynamic policy elements (e.g. CSP nonces)

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#20]
**Problem**
As outlined in the document, a baseline or fallback CSP would be a cool feature. To make this an actual usable feature we need to incorporate dynamic parts like nonces.

**Proposal**
A manifest allows to define CSPs as always except for nonces where Origin Policy templates CSP. It either expects no nonce value at all or simply replaces any given nonce on receiving a new one.
New nonce values are transmitted with the response that also confirms the version of the currently cached manifest. The response header value will be JSON fromatted.

**Example**
CSP in Manifest: `script-src 'nonce-PRETTYRANDOM' ` or simply `script-src 'nonce'`
The server response: `Sec-Origin-Policy: { "version": "policy-1", "nonce": "NEWNONCE" }`

**Comment by annevk** [comment]
Why can't you just have `Content-Securyt-Policy: srcipt-src 'nonce-NEWNONCE'` as additional header besides `Sec-Origin-Policy`?

**Comment by dhausknecht** [comment]
because that is different from `srcipt-src 'nonce-NEWNONCE' 'strict-dynamic'` which you could have defined in your manifest. Sure you could also simply send this CSP here instead. But the goal of Origin Policy is to avoid sending all your headers again and again and again. So I was looking for a way to only transmit what must be transmitted but nothing else.

**Comment by dhausknecht** [comment]
When opening this issue I missed the already [closed issue](https://github.com/WICG/origin-policy/issues/2) on this.
Nevertheless I think one of the purposes of Origin Policy is to centralize and with it simplify things. So creating something that expects you to define your tailored headers for every response anyway does not take anything away from the developers nor the network traffic. Origin Policy would fail its purpose.
So for a developer it is kind of pointless to make the effort defining a manifest. That's why I strongly argue for a cleaner approach than the complex result of the already [closed discussion](https://github.com/WICG/origin-policy/issues/2) to make life easier for normal developers who hardly understand CSP (or any other security header) anyway.

(normal developer == rest of the web below the top 10 domains)

**Comment by mikewest** [comment]
> When opening this issue I missed the already closed issue on this.

I think I still agree with @arturjanc agreeing with me in https://github.com/WICG/origin-policy/issues/2#issuecomment-235527380. :) The fallback/baseline mechanism is meant to deal with this use case, and I think it does so pretty cleanly.

> So creating something that expects you to define your tailored headers for every response anyway does not take anything away from the developers nor the network traffic.

For example, let's look at https://bugs.chromium.org/p/chromium/issues/list, which serves a policy like `default-src https: ; script-src 'report-sample' 'unsafe-inline' 'strict-dynamic' https://www.gstatic.com/recaptcha/api2/ 'self' 'nonce-wqUTkskvMeVXt1FN2og5T1b47NlRv5I8'; child-src https://www.google.com/recaptcha/; frame-src https://www.google.com/recaptcha/; img-src https: data: blob: ; style-src https: 'unsafe-inline'; object-src 'none'; base-uri 'none'; report-uri /csp.do`

That could be represented as a baseline policy of `default-src https: ; child-src https://www.google.com/recaptcha/; frame-src https://www.google.com/recaptcha/; img-src https: data: blob: ; style-src https: 'unsafe-inline'; object-src 'none'; base-uri 'none'; report-uri /csp.do`, and a policy delivered with the response of `script-src 'strict-dynamic' 'nonce-wqUTkskvMeVXt1FN2og5T1b47NlRv5I8';` (note that we don't need the `unsafe-inline` or host list, as we can assume that anyone who supports origin policy also supports a reasonable implementation of CSP). That doesn't look bad to me. It avoids repeating the bulk of the policy, and seems significantly simpler for developers to grok than trying to map variables from an `Origin-Policy` header into an injected CSP header.

**Comment by domenic** [comment]
I agree with the previous takes on this issue; the extra complexity does not pay for itself compared to just layering CSPs on top of each other. Let's close.
