### ISSUE TITLE
24hr max max-age on manifest

### ISSUE THREAD

**Issue by jakearchibald** [mikewest/origin-policy#24]
(raised in https://github.com/WICG/origin-policy/issues/22)

Is it possible to deploy an origin policy that turns all fetches (client & subresources) into network errors? Is it possible that this would also prevent updating the origin policy?

I don't have an exact case in mind, but it might involve the origin manifest containing an entry for "Sec-Origin-Policy". Or it might be as simple as a CSP rule that disallows everything.

If so, we might need a 24hr max max-age like we have with service worker, so if a broken origin policy is deployed, it doesn't lock users out of a site forever.

**Comment by mikewest** [comment]
It's 100% possible for an origin to assert a policy that would break all of its pages. I don't believe it would be possible for the origin to assert a policy that would prevent it from clearing out/replacing the policy (via a new `Sec-Origin-Policy` response header). At a minimum, we could allow it to do so by sending the header along with the response to a service worker ping. *shrug*

Worth adding a section to the spec, regardless.

**Comment by jakearchibald** [comment]
> I don't believe it would be possible for the origin to assert a policy that would prevent it from clearing out/replacing the policy

I think as long as that's true, the 24hr max isn't needed.

**Comment by domenic** [comment]
This remains not-needed with the latest [version negotiation design](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md), so let's close the issue. Notably, that document explains how the "kill switch" use case is very important.
