### ISSUE TITLE
Fetch manifests on redirects

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#27]
**Example**:
`http://redirect.com/first` responses with a redirect to `http://redirect.com/second` which redirects again to `http://a.com`.
redirect.com might want to configure itself through a Origin Policy that affects the second and third redirect request, for example setting HSTS. I am not sure how referrers are handled for redirects from `redirect.com` to `a.com` but a Referrer Policy might also be interesting.

**Question:** Should we fetch the Origin Policy manifest on redirects?

**Comment by annevk** [comment]
As long as the redirect is not exposed, I think so.

**Comment by annevk** [comment]
Though between first and second the origin policy should be the same, no?

**Comment by dhausknecht** [comment]
> Though between first and second the origin policy should be the same, no?

yes, same origin -> same manifest

I was asking mainly because technically we are not landing on the page and the draft so far only talked about responses (sorry I forgot to mention that before).

**Comment by annevk** [comment]
What you want to do is figure out how to integrate with https://fetch.spec.whatwg.org/. Then it'll be more clear how this works (and also make it clear that origin policies won't be fetched from service workers (I'm assuming) and cannot be populated by them).
