### ISSUE TITLE
Origin Policy manifest fetching and HTTP

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#28]
> This [Sec-Origin-Policy] header MUST be ignored if Secure Contexts §is-url-trustworthy returns "Not Trustworthy" when executed upon the response’s URL.

Which basically means "Ignore Sec-Origin-Policy over HTTP". Do we need to do that? I think it's enough to just say "If the response is HTTPS we require HTTPS for manifest fetching". But in fact we respect that already anyway by re-using the response's origin to generate the OP manifest URL.

As we know HSTS and other critical headers are ignored when received over HTTP. Now let's assume `http://a.com` uses the Origin Policy mechanism. The `http:` leaves connections open for our man-in-the-middle attacker MitM.

1. The browser visits `http://a.com/insecure` and with it the browser tries to download the manifest file M from `http://a.com/.wellknown/M`. MitM can intercept and modify M to include for example HSTS or HPKP. Let's call the modified version M_mod. The headers are added to the response for `http://a.com/insecure` but are ignored because HTTP.

2. The same browser now visits `https://a.com/supersecure`. Though "M" (actually M_mod but the browser thinks it's M) is already in cache the protocol is different and therefore the origin. So it re-downloads M but now over `https://`. Since now we use `https:` MitM cannot tamper with it.

Regarding 1., with or without manifest file it is the same situation in terms of security, everything is open to MitM. No changes here. But allowing Origin Policy for HTTP will introduce all the advantages of Origin Policy (like you need to send less headers, you might skip CORS preflights, etc) to insecure connections.

**Comment by annevk** [comment]
Sounds like https://github.com/w3ctag/design-principles/pull/75 would be a good read. The basic idea some of us have (not all yet unfortunately) is that we'd like to move everyone to HTTPS. Offering useful features over HTTP works against that.

**Comment by dhausknecht** [comment]
hm, thanks for your reply. I read it as "yes, you're right. But no goodies for HTTP no more. So no." Well, at least I understand the reason for this restriction now... and I wasn't wrong in principle ;-)
