### ISSUE TITLE
JSON parsing not defined

### ISSUE THREAD

**Issue by annevk** [mikewest/origin-policy#32]
You probably want to put the result of applying https://infra.spec.whatwg.org/#parse-json-from-bytes to the body into the store rather than an unparsed body.

**Comment by domenic** [comment]
Note that parse JSON from bytes returns a JS object, so operating on it is a bit cumbersome: e.g. https://w3c.github.io/payment-method-manifest/#validate-and-parse steps 3 onward. I wonder if we want to make this easier by letting Infra have some way of converting to ordered maps and lists.

**Comment by annevk** [comment]
@domenic in https://github.com/w3c/manifest/issues/611 there was some talk about reusing dictionaries so you could have some type checking too. That way we'd also handle all that in a consistent format across JSON-consuming end points, which seem to be on the rise.

**Comment by domenic** [comment]
Yeah, as long as you are OK treating 123 as "123" or "0xFF" as 255, etc.

**Comment by annevk** [comment]
@domenic yeah, dunno, it seems given the limited amount of JSON values we could have something simpler here and just reject incorrect types. But then instead of dictionaries we'd need some kind of "JSON resource description".

**Comment by domenic** [comment]
My thinking was that if Infra had a way to convert to lists/ordered maps containing JS strings, booleans, and numbers, that would be enough, as then specs could write prose to validate, like the linked PMI spec does. It is a bit more work, I agree. Maybe we should encourage people to use JSON schema? I kind of doubt implementers will want to pull in a JSON schema library though. (I guess it's also doubtful they'd want their network code calling into their IDL bindings though?)

**Comment by annevk** [comment]
This wouldn't happen in the networking layer and I don't think we want to reject if it doesn't match the schema (precludes extensions, just ignore the field). I guess if everyone takes care about ignoring when there's not a type match it can be okay, but folks are already asking to elevate that work as you can see from the linked thread. Anyway, I agree we should do something here and try to make sure we end up with somewhat consistent processing models.

**Comment by domenic** [comment]
I'm currently bullish on the approach I've taken for import maps here. It's somewhat manual, and could probably benefit from more author-facing guidance, but technically it seems sound. See https://wicg.github.io/import-maps/#parsing

**Comment by domenic** [comment]
It's defined now! https://wicg.github.io/origin-policy/#parsing
