### ISSUE TITLE
CSP without policy attribute

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#34]
**Problem:**
Imagine an manifest file with CSP defined but with one of the objects not having a `"policy"` attribute like in
```
"content-security-policy": [{
  "disposition": "enforce",
  "allow-override": true
}],
```

**Question:**
How to handle CSP without a `"policy"` attribute?

**Discussion:**
Eventually we apply whatever CSP defines. So we would be good. But it seems a bit silly to me to actually process it at all. IMO we have the following three options:

1. Keep it and let CSP itself handle it (which should be ignoring it later on anyway)
2. Make the manifest JSON parser ignore it as if it never got added to the manifest
3. Apply a default CSP policy as it is done for Chrome browser extensions

In case other attributes are missing, that is the `disposition` or the `allow-override` as defined in https://github.com/WICG/origin-policy/issues/19#issuecomment-321229817, I currently apply "enforce" and "false" as default values. Though this might be up for discussion as well, I find them far less "dramatic".

**Comment by annevk** [comment]
What's the observable difference between 1 and 2?

**Comment by dhausknecht** [comment]
> observable difference

I don't think there is one. It probably more about how naively to keep the definitions in memory. So we could merge 1 and 2 with the comment "implementation detail".

**Comment by annevk** [comment]
1/2 seems better than having some kind of default policy.

**Comment by domenic** [comment]
The format has changed, so this generally isn't as confusing. But indeed, let's not add any sort of default policy.
