### ISSUE TITLE
Multi-definition of configurations

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#35]
**Problem:**
Consider the following policy
```
{
  "hsts": { ... },
  "hsts": { ... }
}
```
JSON accepts this as valid JSON but when parsing only takes the last definition into account.

**Question:**
Do we rely on this JSON behaviour implicitly?

**Discussion:**
I personally would like to see this explicitly defined to be clear about the behaviour. This is important especially when it comes to configurations like for HSTS. For example for CSP we could easily merge multi-definitions as it was only one since based on https://github.com/WICG/origin-policy/issues/19#issuecomment-321229817 we will have a list as its value.

(The question was raised by Lucas Garron on https://groups.google.com/a/chromium.org/d/msg/blink-dev/mdkHs4jybG4/EBOVwTifAQAJ)

**Comment by annevk** [comment]
I think we need to use the hook in #32. Whatever that ends up returning we can operate on, but we shouldn't try to introduce any special behavior at a lower level.

**Comment by lgarron** [comment]
> {
>   "hsts": { ... },
>   "hsts": { ... }
> }

Just to be clear, that should be `Strict-Transport-Security` in a real policy, right?

**Comment by dhausknecht** [comment]
now we are in a situation where discussions and status of the draft do not match anymore (shame on us). Please read https://github.com/WICG/origin-policy/issues/19#issuecomment-321229817 for how we currently think the JSON will look like.

So "hsts" is wrong in any case, it should be "tls". But that is detail. Important is that we no longer want to be directly tied to headers but to concepts. Then we can basically do what we want and no longer have to follow header definitions directly. Besides, things like CORS are not simple headers and will fit in much better now.

**Comment by domenic** [comment]
Rolling this in to #32. Although I can tell you that we'll be using https://infra.spec.whatwg.org/#parse-json-from-bytes which picks the second one.

Certainly something to remember to write web platform tests for.
