### ISSUE TITLE
Consider different OP announcement value

### ISSUE THREAD

**Issue by otherdaniel** [mikewest/origin-policy#40]
We ran into an issue in our implementation, where Origin Policy unnecessarily inflates an otherwise minor bug in header processing:

When (a faulty server | faulty proxy | faulty client) erroneously copies request headers into the response, and this also affects the Origin Policy announcement header (sec-origin-policy: 1), then this has the unfortunate effect of locking down the entire site. Furthermore, since the site operator is presumably not aware of the issue, they likely haven't prepared for sending the right header to delete the policy.

Reference: https://crbug.com/901477

As a work-around, we have chosen to advertise OP capability using the sentinel value for deleting a policy. (sec-origin-policy: 0)

Alternatives would be:
- Different header names for request and response.
- Using a value to announce capability that isn't a valid policy name.

**Comment by annevk** [comment]
A different header for the response seems good. I don't think there's precedent for `Sec-` prefixed response headers and it seems somewhat confusing to start with that.
