### ISSUE TITLE
Limit entropy of Sec-Origin-Policy request header

### ISSUE THREAD

**Issue by michael-oneill** [mikewest/origin-policy#41]
Would it work if the value in the Sec-Origin-Policy request header was an entropy limited hash (say 16 bits) of the Origin Policy content. The server could check it against the current OP to decide whether to initiate a Push, alleviating the privacy risk. If a new OP created a hash collision with a previous version, then an extra space could be recursively added to the content to avoid it.

**Comment by mikewest** [comment]
Let's fold any discussion here into https://github.com/WICG/origin-policy/issues/23.
