### ISSUE TITLE
"version" is a confusing term

### ISSUE THREAD

**Issue by MattMenke2** [mikewest/origin-policy#43]
I'd generally interpret "version" to be a monotonically increasing value, with newer/higher versions superseding earlier versions.  While "version" can be used in other contexts, where versions don't necessarily replace each other, I think it's more confusion than necessary.  Can we call them policies, policy sets, configurations, or something without the implication?

Another option would be to explicitly define version as its intended use, as oppose to just specifying how to get it and how to use it (Which are a far cry from a plain text definition).

**Comment by annevk** [comment]
FWIW, you probably want to look at https://github.com/WICG/origin-policy/issues/23#issuecomment-494880350 and comment on the document linked from there.

**Comment by domenic** [comment]
It is now "id" in the explainer. (Spec update to happen soon.)
