### ISSUE TITLE
PR #29 fixed a typo in index.src.html but not in index.html

### ISSUE THREAD

**Issue by nhnt11** [mikewest/origin-policy#45]
Not sure if the src file just needs to be recompiled to html. The document hosted at https://wicg.github.io/origin-policy/ still has the typo.

**Comment by domenic** [comment]
Fixed by https://github.com/WICG/origin-policy/commit/c3be6b3b84c92a8e49fce1a5eca91a7eb70c4158 (and should no longer be possible now that deploys are done automatically instead of by humans).
