### ISSUE TITLE
Which takes precedence, origin policy or headers?

### ISSUE THREAD

**Issue by amtunlimited** [mikewest/origin-policy#46]
If a response header (HSTS, CSP, Feature Policy) conflicts with the origin manifest, which one wins? Intuition says headers, but it's not discussed (or I couldn't find it). I would suspect the more specific scope would win, but I don't know if this is more generally defined elsewhere.

**Comment by domenic** [comment]
This is now covered, on a per-policy basis, in https://github.com/WICG/origin-policy/blob/master/policy-format.md, at least for CSP and Feature Policy. I will add similar notes for the other policy items that have corresponding headers.
