### ISSUE TITLE
Allow page to know from JavaScript what policy was applied

### ISSUE THREAD

**Issue by domenic** [mikewest/origin-policy#48]
Given an async update model (see the [latest plans for version negotiation](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md)), where you have a list of allowed policies (which could include "none") plus a preferred policy, pages may want to know which policy actually got applied.

For example, consider a landing page with less-sensitive things, which allows the none policy. When the user goes to login, if the none policy was applied, then they'll do a normal browser navigation, so that when they enter the sensitive portion of the site, the preferred origin policy is applied. But if the preferred policy was applied, they'll do a nice Ajax navigation with some swooshy transitions.

I propose we add something like `self.originPolicy` which allows the page to tell what got applied in this way.

Details to figure out:

- `originPolicy`, or `originPolicyId`? The former is shorter; the latter is perhaps more accurate.
- `self.originPolicy`, or `self.originPolicy` in workers and `document.originPolicy` in documents? It seems like origin policies will be applied per-Document, not per-Window, so splitting them makes more architectural sense. But that's more awkward for developers.

**Comment by domenic** [comment]
This would make testing significantly easier, so I'm inclined to include it sooner rather than later. Any objections?

**Comment by annevk** [comment]
I think this is fine, it also avoids the risk of sites using some Origin Policy "subpolicy" to signal this as a side effect of something.

**Comment by domenic** [comment]
This gets a bit messier now that the manifest has multiple IDs, and not a single ID, but I guess a frozen array works fine. And at least the naming question is resolved; `self.originPolicyIds` seems obviously correct now.

**Comment by domenic** [comment]
Any thoughts on whether no origin policy (i.e. the null origin policy) should be signaled via `null`, or via the empty array?

**Comment by Sora2455** [comment]
To me personally, an empty array makes more sense (which Origin Policy got applied? None!).
