### ISSUE TITLE
Error handling discussion

### ISSUE THREAD

**Issue by domenic** [mikewest/origin-policy#49]
There are multiple potential errors that could occur with an origin policy:

1. Network errors for fetching the origin policy
2. HTTP error responses (non-2xx) for fetching the origin policy
3. Origin policy is not parseable as JSON (e.g. missing comma)
4. Origin policy is parseable as JSON but does not match [the schema](https://github.com/WICG/origin-policy/blob/master/policy-format.md):
    1. The contents of the document are not an object, e.g. are an array or true or false or null.
    1. Has an invalid identifier, most notably the reserved identifier `"id": "none"`
    1. Contains unknown top-level keys
    1. Contains invalid values for a specific key (e.g. a non-object for `"content-security"`)
    1. Contains invalid per-feature values (e.g. the value for the CSP is not parseable as a CSP).
5. The [`Origin-Policy` header](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md) is unparseable according to the structured headers spec.
6. The `Origin-Policy` header is parseable but mismatches the schema:
    1. Contains invalid keys besides allowed/preferred
    1. `allowed`'s value is not a list.
7. There is no origin policy cached, nor available at `/.well-known/origin-policy`, which matches the `allowed=()` value in the `Origin-Policy` header.

Probably there are more.

Which of these errors should cause a "hard failure", i.e. a network error for any responses to which the origin policy would apply, potentially resulting in a user-facing interstitial, vs. a "soft failure", i.e. just proceeding with the null origin policy applied to the response?

People have mostly advocated for soft-failure so far. (7) has to be a hard failure, as it's specifically designed as a mechanism for causing hard failure. I'm wondering if there are any other cases from the above list (or elsewhere) where hard failure is appropriate.

There's also a distinction between types of soft failures: ones that invalidate the origin policy, and ones which can be ignored. So e.g. (4.ii) seems like it would invalidate the origin policy, whereas (4.iii) seems like it should be ignored. Note that invalidating an origin policy can lead to hard failure (7) if a restrictive `allow=()` list is in play.

But, let's first focus on hard vs. soft, and then nail down the types of soft. Are there any things in this list people think should be hard failures?

**Comment by annevk** [comment]
Not a valid MIME type is another issue. (I wonder if we should require a specific MIME type?)

I think we have to be graceful for a lot of these for extensibility reasons and also to allow for bad network conditions. Also, given 7, we can make matters more strict down the line via opt-in in the initial policy if there's an articulated need to do so.

As for invalidation, I wouldn't invalidate on any failure and let `Origin-Policy` decide what to do with the cached copy.

**Comment by domenic** [comment]
I agree we generally want to fail soft. I'm just unsure how far that extends. E.g. Chrome's flagged implementation currently fails hard for malformed JSON (3). Should that fail soft too?

**Comment by annevk** [comment]
I don't really see a principled reason to treat those errors differently from the others. And bricking someone's site when the wrong file is uploaded isn't great. Not being able to find an `Origin-Policy` allowed policy is different however as you need that to continue.

**Comment by domenic** [comment]
This is tentatively covered in https://github.com/WICG/origin-policy/blob/master/policy-format.md#error-handling, so I'll close. Still need to do the spec work, and of course the tests.
