### ISSUE TITLE
Clarify HTML integration algorithm

### ISSUE THREAD

**Issue by shekyan** [mikewest/origin-policy#5]
From `#monkey-patching-html`, it is not clear what happens if fetch fails to get the response in reasonable timeline and there are no cached policy. Do we block the rendering? Do we render anyway?

I can see how people would put a dedicated web server to serve manifests behind a load balancer, which opens attack vectors like DoS.

**Comment by mikewest** [comment]
Yup, if the manifest fetch fails, we should fail the request which triggered the manifest. Thanks for noting that I didn't describe that.
