### ISSUE TITLE
Inconsistency between CSP and Feature Policy formats

### ISSUE THREAD

**Issue by domenic** [mikewest/origin-policy#50]
https://github.com/WICG/origin-policy/blob/master/policy-format.md has `"features"` as a single string, and `"Content-Security-Policy"` as an array of strings.

For CSP it states

> Note that - just as the headers - you can chain multiple policies by either listing them as seperate strings in the array of strings, or by merging them into one string and separating them by a semicolon.

I'm trying to understand whether we can converge these, or whether the divergence is intentional. Some questions:

- Are multiple FP headers processed significantly differently from multiple CSP headers?
- Why does that note talk about semicolon-joining CSP headers, when multiple HTTP headers are usually comma-joined? (i.e. `H: 1\nH: 2` should be equivalent to `H: 1,2` generally speaking.)

/cc @clelland @mikewest

**Comment by mikewest** [comment]
> Are multiple FP headers processed significantly differently from multiple CSP headers?

https://w3c.github.io/webappsec-csp/#multiple-policies describes the effect of multiple policies applied to a page. https://csp.withgoogle.com/docs/faq.html#strict-dynamic-with-whitelists is an example of how it can be a meaningful and useful thing to do.

@clelland will correct me if I'm wrong, but I believe that feature policy made different decisions, combining all the policies together into one policy via a merging operation defined in https://w3c.github.io/webappsec-feature-policy/#algo-process-response-policy.

> Why does that note talk about semicolon-joining CSP headers

The "semicolon" reference is likely a typo. I agree that it should read "comma" instead.

**Comment by domenic** [comment]
OK, cool. So then, it seems like for both FP and CSP, `H: 1\nH: 2` is equivalent to `H: 1,2`, and multiple headers is just a convenience feature to make reading/writing the combined policy a bit nicer.

In that case, it seems like we should be able to make the same decision for both CSP and FP as to whether to use arrays or not.

So I guess the question is, do we want to have two ways to do something in origin policy, like we do with HTTP headers? I.e. do we want to allow `['1', '2']` as a potential alternative to `'1, 2'`?

My leaning is no: it seems like this is an unnecessary carryover from the header-based descriptions, and just makes the model more complicated. But I could definitely be missing something.

**Comment by annevk** [comment]
I agree, Origin Policy should have its own syntax. It can be based on existing syntax where appropriate, but it shouldn't be constrained by it. It does have to map to the same underlying data model.

**Comment by clelland** [comment]
@mikewest, that's right; feature policy doesn't have the concept of multiple overlaid policy directives that CSP does.

@domenic, isn't that necessary for HTTP headers in general? RFC7230 says

    A recipient MAY combine multiple header fields with the same field
    name into one "field-name: field-value" pair, without changing the
    semantics of the message, by appending each subsequent field value to
    the combined field value in order, separated by a comma.

and that's regardless of the semantics of the specific header in question.

**Comment by mikewest** [comment]
> it seems like this is an unnecessary carryover from the header-based descriptions

I think there's an actual difference. There can be multiple Content Security Policies applied to a context, each of which may have a distinct effect on that context's behavior, while there can be only one Feature Policy.

In HTTP we represent multiple CSPs via multiple headers (comma separated as per HTTP's combination rules). As @annevk notes, there's no particular reason to be constrained by HTTP's syntax when representing this multiplicity of policies in a different, perhaps more expressive medium. If we're using JSON anyway, representing multiple policies via multiple entries in an array seems pretty reasonable.

I don't have a strong opinion on the one string vs multiple string question, but I do think it would be a good idea for us to move away from header-style representations generally. It's probably fine for the existing mechanisms we're porting into Origin Policy, but I'd eventually like to set precedent for configuration options with semantic meaning, rather than just a string that requires additional parsing.

**Comment by domenic** [comment]
Hmm. I'm not sure I understand the CSP model well enough to distinguish between "multiple CSPs" versus "one CSP with commas inside it". In particular, I guess they are isomorphic at the HTTP header level, but you are maybe making a distinction at the mental model level?

And in particular I'm unsure whether the distinction between those is significantly different than that for feature policy. Both define the ability to have multiple policies / a single policy with commas inside of them, and both give well-defined semantics for merging the things after a comma with the things before the comma.

Is the argument you're making that it's more common for people to use comma-containing CSP, than it is for people to use a comma-containing FP? Should we consider disallowing comma-containing FPs?

**Comment by domenic** [comment]
@mikewest ping! Still trying to get this straightened out in my head. Or I'm happy to discuss over VC if you think higher-bandwidth communication would be better.

**Comment by mikewest** [comment]
@domenic: You're entirely correct that multiple CSPs can be represented by one, comma-delimited string. The HTTP header value "directive1; directive2, directive3" is parsed as two policies: « `directive1`, `directive2` » and « `directive3` ».

Feature Policy, on the other hand, would parse "directive1; directive2, directive3" as one policy: « `directive1`, `directive2`, `directive3` ».

My claim is that comma-separated strings yield behavioral differences in CSP that cannot be expressed in a single policy: again, I'd point to https://csp.withgoogle.com/docs/faq.html#strict-dynamic-with-whitelists.

This is not the case in Feature Policy. I think this behavioral difference means that it's reasonable to treat them differently in an origin's manifest.

That said, I'm not actually sure what syntax this thread is debating at this point. :) I'm happy to hop on a call if it's helpful?

**Comment by domenic** [comment]
> That said, I'm not actually sure what syntax this thread is debating at this point. :)

Well, I'm trying to figure out what the format should be for the FP and CSP origin policy members, since we are no longer looking at a 1:1 header isomorphism via the `"headers"` member.

I think as a starting point, we want to recognize what origin policy is meant to communicate in each case:

- For CSP, it is meant to communicate a CSP list. (A list of lists of directives.)
- For FP, it is meant to communicate a FP. (A list of directives.)

Then the question becomes, how do we express these things in origin policy?

One option is to just express the serialization in both cases. For a CSP list, the serialization is a comma-delimited string of semicolon-delimited directives. For FP, it appears the serialization is a comma-or-semicolon-delimited string of directives. That's fairly simple.

```json
{
  "features": { "policy":
    "geolocation 'self' https://example.com; sync-xhr 'none'"
  },
  "content_security": { "policies":
    "script-src foo.example.org bar.example.org 'unsafe-inline'; object-src 'none', script-src 'nonce-random123' 'strict-dynamic' 'unsafe-inline' https:"
  }
}
```

If we depart from the serialization approach, then we have to decide at what level we transition between structured data and serialized strings. For example:

- We could say that CSP lists are treated as structured data, and use arrays, but CSPs and FPs are given in serialized form.

    ```json
    {
      "features": { "policy":
        "geolocation 'self' https://example.com; sync-xhr 'none'"
      },
      "content_security": { "policies": [
        "script-src foo.example.org bar.example.org 'unsafe-inline'; object-src 'none'",
        "script-src 'nonce-random123' 'strict-dynamic' 'unsafe-inline' https:"
      ] }
    }
    ```
  
- We could say that CSP lists, CSPs and FPs are treated as structured data, and use arrays, but their directives are given in serialized form.

    ```json
    {
      "features": { "policy": [
        "geolocation 'self' https://example.com",
        "sync-xhr 'none'"
      ] },
      "content_security": { "policies": [
        [
          "script-src foo.example.org bar.example.org 'unsafe-inline'",
          "object-src 'none'"
        ],
        [
          "script-src 'nonce-random123' 'strict-dynamic' 'unsafe-inline' https:"
        ]
      ] }
    }
    ```
 
 - We could do the above, plus use dictionaries for the directives within a given CSP and FP, instead of directive strings:

    ```json
    {
      "features": { "policy": [
        "geolocation 'self' https://example.com",
        "sync-xhr 'none'"
      ] },
      "content_security": { "policies": [
        {
          "script-src": "foo.example.org bar.example.org 'unsafe-inline'",
          "object-src": "'none'"
        },
        {
          "script-src": "'nonce-random123' 'strict-dynamic' 'unsafe-inline' https:"
        }
      ] }
    }
    ```

- Maybe there is even structure within the directive values we could use.

Anyway, what I'm hearing is an argument for treating CSP lists as structured data, but giving CSPs and FPs in serialized form. If we were to do this, I think we'd want to do two things in particular:

- Distinguish between CSP lists and FPs, e.g. as I have done above by using `"policies"` for CSP lists and `"policy"` for feature policy.
- Do not allow putting CSP list serializations in places where CSP serializations are expected. I.e., if a comma appears inside a CSP string, that is an error; we don't treat it like an array in disguise.

I think a coherent alternative is to just use the serialization in both cases, and no arrays, but it seems like you prefer having at least some structured data.

Thoughts?

**Comment by domenic** [comment]
Current plan:

- Use `"policies"` for CSP, whose values is an array representing a CSP list. Each individual string in the array is parsed using [the CSP parser](https://w3c.github.io/webappsec-csp/#abstract-opdef-parse-a-serialized-csp) (not [the CSP list parser](https://w3c.github.io/webappsec-csp/#abstract-opdef-parse-a-serialized-csp-list)). So, commas will not work inside the string.
- Use `"policy"` for FP, whose value is a string representing a FP and is parsed using [parse policy directive](https://w3c.github.io/webappsec-feature-policy/#algo-parse-policy-directive). So, commas will not work inside the string.
