### ISSUE TITLE
Mapping from response header to URL

### ISSUE THREAD

**Issue by martinthomson** [mikewest/origin-policy#7]
The example says:

```
Origin-Policy: "policy-1"
```

Which is then somehow turned into `/.well-known/origin-policy/v1`.

This might be an error, but I can't tell from the text in [Section 2.3.1](https://mikewest.github.io/origin-policy/#origin-policy-well-known).

**Comment by mikewest** [comment]
Thanks. That was leftover from a previous iteration. And it's going to change again in a minute! Hooray for early days of a draft...
