### ISSUE TITLE
Vary, request headers, and telling what policy has been applied

### ISSUE THREAD

**Issue by mnot** [mikewest/origin-policy#77]
(Apologies if I've missed some context here)

The examples have `Vary: origin-policy`, but `Origin-Policy` is defined as a response header.

What's the intent here? Or is this just left over from a previous revision?

Note that in the current design, there isn't a way for an origin to know when it can omit response headers that are subsumed by OP (e.g., CSP). That seems like a shame, as it means that the only savings seen by OP will be when all clients support it, or when a feature only uses OP, not response headers.

To support that, requests would need to indicate what policy they've applied; is there any interest in bringing that back? Now that we have Client Hints, it seems like we've got a framework for addressing the inherent privacy concerns in doing so...

**Comment by domenic** [comment]
Thanks, the `Vary` is indeed leftover.

> Note that in the current design, there isn't a way for an origin to know when it can omit response headers that are subsumed by OP (e.g., CSP). That seems like a shame, as it means that the only savings seen by OP will be when all clients support it, or when a feature only uses OP, not response headers.

Yes! This is the subject of  #51, which I asked for your thoughts on a while back :). I'd love to hear what you think over there?

(I'll close this issue with a PR to remove the leftover `Vary`.)
