### ISSUE TITLE
Parameters on Structured Headers

### ISSUE THREAD

**Issue by mnot** [mikewest/origin-policy#78]
(Apologies if I've missed some context here)

The current draft says:

> No parameters are used in any locations within the structured header.

Is there a risk that someone will read this to mean that they're prohibited / parsing should fail if they occur?

**Comment by domenic** [comment]
I'm not sure. The parsing algorithm is given pretty explicitly, and ignores them, per

> The processing model for this header, including the fallback behavior for when it is not provided or does not conform to the above data model, is given in § 4.1 Response processing. 

But if you have suggestions for other phrasing which would make it clearer that no parameters are used, while not potentially leading people to believe they will cause header rejection, I'd be happy to incorporate it.

**Comment by mnot** [comment]
I think you can just omit the sentence, but if you want to keep the sentiment, something like

> This specification does not currently use parameters on the structures it defines.

would be better IMO. 

Not a big deal, just seemed odd when I was reading it.
