### ISSUE TITLE
potential performance issues with fetching origin policy

### ISSUE THREAD

**Issue by wanderview** [mikewest/origin-policy#86]
Reading the spec it appears that a fetch is made to both load a new origin policy from the network and also to load a cached origin policy out of the http cache.  This is seems to be done on the navigation request and every subresource request.  Is this correct?

If so, doubling the number of network stack operations for every subresource seems like a very large amount of overhead.  In addition, if a service worker is present its possible FetchEvents will be fired for these as well (see #85 ).  Even if the request are hitting http cache or the service worker cache_storage this is could be a lot of overhead.

Would it be possible to provide some kind of in-memory cache with a limited age on the client itself?

**Comment by domenic** [comment]
Did you see the note in the spec that says that implementations can (and likely will) use different strategies, such as in-memory caches, as long as they are observably equivalent? Combined with the skip-service-worker flag, I don't anticipate a significant performance overhead here.

**Comment by wanderview** [comment]
Hmm, I did not, but I do now.

I guess I wonder if this should be left to a non-normative note.  I think we've seen the unspec'd memory cache in chromium cause subtle interop issues in the past.

Also, as I mentioned in the other bug I don't understand why the service worker is bypassed.  If a FetchEvent was triggered then origin policy could work deterministically for fully offline sites.  That's not possible with the current spec AFAICT, since http cache could evict at any time.  If service worker is consulted, though, then any memory caching would become observable and might need a more formal spec.

**Comment by domenic** [comment]
> I guess I wonder if this should be left to a non-normative note. I think we've seen the unspec'd memory cache in chromium cause subtle interop issues in the past.

What would the normative text say? The only thing I can imagine is "please implement the above normative text as normative, even if you do optimizations. Bugs are not allowed." Which seems kind of redundant.

> Also, as I mentioned in the other bug I don't understand why the service worker is bypassed.

Let's discuss that in the other bug.

**Comment by wanderview** [comment]
Waving hands at memory cache seems to solve this.  I worry that its required for the spec to be implementable in practice, though.  Closing this.
