### ISSUE TITLE
Strictness in header parsing

### ISSUE THREAD

**Issue by domenic** [mikewest/origin-policy#87]
While implementing https://wicg.github.io/origin-policy/#parse-an-origin-policy-header I noticed that the algorithm is a bit strict, returning "unparseable" in cases where we could instead skip over things. In particular:

1. If your top-level is not a dictionary, we return "unparseable". This is probably fine.
2. If your `allowed` dictionary entry is not a list, we return "unparseable". Instead we could just treat this as if you did not include `allowed`.
3. If your `allowed` list contains any list items that are not the `latest` token or the `null` token or a string, we return "unparseable". Instead we could just skip those items.
4. If your `preferred` dictionary entry's value is not the `latest-from-network` token or a string, we return "unparseable". Instead we could just treat this as if you did not include `preferred`.

I'm inclined to switch the behavior on (3) and (4), and weakly inclined to do so for (2) as well.

Any thoughts from the structured-header-using people I know? This is an evolving space and it'd be ideal if we all aligned on best practices. @mnot @annevk @clelland @jyasskin

**Comment by jyasskin** [comment]
I think the current thinking here is described by @martinthomson's https://tools.ietf.org/html/draft-iab-protocol-maintenance. I haven't read it recently, so others may correct me on how to apply it to this case, but I'll try anyway.

If the checks in (2), (3), and (4) are about catching bugs in the peer implementation, then they're correct to fail in the loudest possible way, which is probably the "unparseable" result. The only reason to avoid doing that is if one of:

1. We think the peer might be unable to do the "right" thing from the parser's perspective. For example, signed exchanges treat an expired signature as not contributing to either trust or distrust instead of rejecting the whole resource, because the peer might have sent it before the expiration time. I don't think this applies here.

2. We think a future version of the protocol might want to specify that the peer do something else, which old parsers need to accept for upgrades to be viable. Is this the reason you're concerned about these cases? If so, is that hinge [GREASEd](https://www.rfc-editor.org/rfc/rfc8701.html) by something else in the protocol?

**Comment by domenic** [comment]
> We think a future version of the protocol might want to specify that the peer do something else, which old parsers need to accept for upgrades to be viable. Is this the reason you're concerned about these cases?

Yes, exactly that.

> If so, is that hinge GREASEd by something else in the protocol?

I'm not really able to understand the meaning of this question by the link provided. Do you have a more specific recommendation?

**Comment by domenic** [comment]
More generally, I was wondering if other structured-header users are doing things like rejecting optional fields if those optional fields have the wrong type (vs. treating the field as absent), or rejecting the entire header if an individual list item has the wrong type (vs. skipping that item when processing the list). Do you know of any specific cases?

**Comment by jyasskin** [comment]
Sorry for the too-concise reference. The idea, originally by Adam Langley, is that ["In complex ecosystems with multiple implementers, unused joints rust shut."](https://blog.cloudflare.com/why-tls-1-3-isnt-in-browsers-yet/#:~:text=In%20complex%20ecosystems%20with%20multiple%20implementers,%20unused%20joints%20rust%20shut.) Even with a specific algorithm, like here, saying to treat unexpected values in a particular way, some implementers are likely to do the wrong thing in such rare cases unless the protocol finds a way to make those cases not rare. In TLS, the particular extension points we want to keep flexible are now "greased" by RFC8701.

In Origin Policy, it's possible that we don't actually have enough implementers for the maxim to apply. But if we do, we'd want to try to find a way to make sure that implementers actually see unexpected tokens in any place we want future versions to be able to see new tokens, or that the simplest possible implementation allows those tokens for some other reason.

One way to do that might be to require that _every_ origin policy include an unexpected token in at least one of these lists. There might be better ways.

My [use of Structured Headers](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#name-the-signature-header) allows new parameters but strictly specifies the types of the existing parameters. I don't have grease specified, but we should think about it as that particular header evolves.

**Comment by martinthomson** [comment]
I think that the discussion of greasing is a side-show here.  The question is what to do when known fields are not valid in terms of their defined semantics.  The defined algorithm is good in that there is never any ambiguity about the two dictionary items that the spec cares about that.

That means that extensions cannot redefine an existing field to allow more types.  That seems like a feature to me.

I would expect extensions to do the same.  So if "foo" is defined as a number and "foo" is present and not a number, the whole thing is invalidated as a result.

Speaking of which, there is no similar strictness in the handling of parameters on field values.  That might be intentional if you intended to allow parameters, but ignore them.  If you intend to disallow parameterized extensions, then that requires text.

**Comment by clelland** [comment]
> 1. If your top-level is not a dictionary, we return "unparseable". This is probably fine.

This is required, I expect -- Structured headers requires that the top-level type be passed to the parsing algorithm, and at that point, any syntactic failure is fatal. Anything after that point is semantic, and I'm inclined to agree with others in the thread that current or future extension points should be well greased, and other things should be strict.

> 2. If your allowed dictionary entry is not a list, we return "unparseable". Instead we could just treat this as if you did not include allowed.

The most common case here is going to be that authors don't include the enclosing parens around the list. sh-dict members can be either an inner list or a single item (anything else would have failed parsing), so we could legitimately accept either. If it is an item, then we could either:

    1. Drop the entire "allow" member as invalid
    2. Accept it as a single item, and make that official syntax

For (3) and (4), forward compatibility is hard. I suspect that numbers or byte sequences will always be invalid, and should be errors (though they're also probably harmless to ignore). I'd like to say that unknown tokens are simply ignored; but that has unknown consequences. If a new token is introduced and used, can we always ensure that ignoring it is safe? Probably for "allowed", but I'm less sure about "preferred".

Re: Parameters -- the spec currently says that it does not use them, which is cool, but the SH spec says "field specifications are discouraged from defining the presence of an unrecognized Parameter as an error condition", so if possible, we should just ignore any parameters that are seen.

**Comment by mnot** [comment]
Just a reminder - if something in this thread can help improve the "Defining New Structured Fields" section of SH, please open an issue over there.

**Comment by domenic** [comment]
Thanks all for the helpful words here. I'm hearing three potential alternatives:

- (A) Be strict. This may pose future compatibility problems, but those can be worked around with UA sniffing (cf. #51).

- (B) Allow some extension points, and GREASE them. In practice I guess this means adding guidance for server operators to send random currently-disallowed values to make sure browsers ignore them. I'm unsure how likely server operators are to follow this advice.

- (C) Allow some extension points, with no GREASE. Instead rely on our usual mechanisms for ensuring browsers follow the spec, i.e. web platform tests. (See, for example, [this test for origin policy JSON parsing](https://github.com/web-platform-tests/wpt/blob/ad9423bf2edd246111d00e6b7bd7f35359bf501f/origin-policy/ids/mix-of-ids.https.html) which asserts against [this input origin policy manifest](https://github.com/web-platform-tests/wpt/blob/ad9423bf2edd246111d00e6b7bd7f35359bf501f/origin-policy/policies/op15%20mix-of-ids.json).)

I'm still unsure how to choose between them, and honestly was really hoping I'd get some answer-from-authority from @mnot or similar saying "this is how we do things now" :). But I can continue noodling.

To some specific questions:

> That means that extensions cannot redefine an existing field to allow more types. That seems like a feature to me.

First note that I'm not really concerned about extensions as much as I am future revisions to the spec.

Next, I'm a bit less concerned about type changes vs. value space changes. From a "type" point of view, the two field types are currently list of strings-or-tokens and string-or-token. But should we skip unknown tokens (outside of the three defined here), or should they cause a parsing failure? @clelland's reply touches a bit on this.

> Speaking of which, there is no similar strictness in the handling of parameters on field values. That might be intentional if you intended to allow parameters, but ignore them.

Correct, that's the intention of the current spec. The non-normative text states "This specification does not currently use parameters in any locations within the structured header it defines", and the normative text repeatedly looks up the 0th item in the parsed tuple, ignoring the 1st item (the parameter list). See also #78.

**Comment by martinthomson** [comment]
@mnot I think that SH is mostly OK.  I sent in a PR that attempts to clarify further though.  I do have one tiny issue to consider below.

@domenic, this is more subtle than what you have in your taxonomy.  The goal is to take the de-facto extension model from JSON and formalize that a little.  Definitions can be strict, but they are encouraged to follow the model that Jeffrey described.  That is, dictionary keys or parameters that you don't know get ignored, but values that you do understand have to be right or the entire header field shares its fate.  That is, if x is an integer, then finding a string causes the header field to be lost as a result.

I think that SH does basically advocate for that view.  I'd be supportive of it saying that even more definitively though.  That is, unless a specification opts out of extension-by-default explicitly, then implementations can assume that new values will be ignored.

**Comment by domenic** [comment]
@martinthomson how would your interpretation apply to the specific questions here? I.e.:

* x is a list of strings or the tokens null or latest-from-network. You find a list containing strings plus the number 5.
* x is as before. You find a list containing strings plus the token asdf.

I.e. it's not clear to me how to deal with the contents of lists, or with unrecognized tokens. I agree parameters and dictionary keys are fairly clear from the model.

**Comment by martinthomson** [comment]
Absent a specific set of rules that allowed 5 or asdf, I would say that those would be fatal as they don't fit the defined content model for the list.

However, and I think I get where you are headed here, something like CSP defines a far richer list-based schema that allows for the addition of new keywords.

The formal model would include both tokens and quotes strings, with specific semantics for null and latest-from-network. You would have to expressly say that unrecogized tokens would have undefined semantics and so MUST be ignored. Numbers would be illegal and would result in losing the entire header field.

That model could be adopted more generally, with advice to match in the core SH spec, but it could be that this is a sufficiently narrow case. I am willing to bet on this CSP-like usage as being special. After all, if this is not general enough, adding generic rules to the core spec as though they were universal might preclude or constrain other valid usage models.

**Comment by domenic** [comment]
Thanks all. In https://github.com/WICG/origin-policy/pull/91 I retained most of the strictness but loosened to skip unknown tokens instead of treating them as errors. Further thoughts and discussion welcome, and I can reopen if someone feels strongly this is incomplete.
